###
GET {{baseUrl}}/auctions/2/bids/stream

###
GET {{baseUrl}}/auctions/3/bids/stream

###
POST {{baseUrl}}/auctions/2/bids
Content-Type: application/json

{
  "amount": "52.43",
  "bidderId": 2
}


