###
GET {{baseUrl}}/auctions/2/bids/stream

###
GET {{baseUrl}}/auctions/3/bids/stream

###
POST {{baseUrl}}/auctions/2/bids
Content-Type: application/json

{
  "amount": "52.43",
  "bidderId": 2
}

###
POST {{baseUrl}}/sellers/5/auctions/8/image
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="auction.png"
Content-Type: image/png

< ./auction.png
--WebAppBoundary--